import pandas as pd

# Load the CSV file
# Assuming the input file is the one generated by the previous script
file_name = "mapped_distances_by_trial.csv" # Or whatever your last output CSV was named
df = pd.read_csv(file_name)

# Ensure the correct column names
TIME_COL = "Time (ms)"
TRIAL_COL = "Trial Number"
GESTURE_COL = "Gesture"
DISTANCE_CHAIR_COL = "Distance Chair"
DISTANCE_BACKPACK_COL = "Distance Backpack"
DISTANCE_DINING_TABLE_COL = "Distance Dining Table"
DISTANCE_COUCH_COL = "Distance Couch"


# Process each trial separately: subtract the first timestamp of each trial
# This transforms the 'Time (ms)' column to be relative to the start of each trial
df[TIME_COL] = df.groupby(TRIAL_COL)[TIME_COL].transform(lambda x: x - x.min())

# Select only the desired columns for the new DataFrame
# Create a list of the columns you want to keep
desired_columns = [
    TIME_COL,
    TRIAL_COL,
    GESTURE_COL,
    DISTANCE_CHAIR_COL,
    DISTANCE_BACKPACK_COL,
    DISTANCE_DINING_TABLE_COL,
    DISTANCE_COUCH_COL
]

# Create a new DataFrame with only the selected columns
df_selected = df[desired_columns]

# Save the updated and selected data to a new CSV file
output_file = "proximity.csv" 
df_selected.to_csv(output_file, index=False)

print(f"✅ Processed data with relative timestamps and selected columns saved as {output_file}")